version: "3.3"
services:
  deliver_back:
    build: 
      context: .
    image: food/deliver:0.0.1
    container_name: deliver_back
    ports:
      - "5000:500"
    depends_on:
      - deliver_db
    
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=postgres
      - PGPASSWORD=12345678
      - PGDATABASE=deliver_db
      - PGHOST=deliver_db
     
  deliver_db:
    container_name: deliver_db
    image: 'postgres:12'
    ports:
      - "5432:5432"
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=12345678
       - POSTGRES_DB=deliver
    volumes:
      - deliver_data:/var/lib/postgresql/data
volumes:
  deliver_data: {}